# Generated by Django 5.1.1 on 2026-07-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Короткий код'),
        ),
    ]
